package me.ilker.balance_tracker.theme

import androidx.compose.ui.graphics.Color

val PrimaryColor = Color(0xFF1E7B24)
val OnPrimaryColor = Color(0xFFFFFFFF)
val PrimaryContainerColor = Color(0xFFBDEFB9)
val OnPrimaryContainerColor = Color(0xFF002204)
val PrimaryDarkColor = Color(0xFF93DE90)
val OnPrimaryDarkColor = Color(0xFF00390B)
val PrimaryDarkContainerColor = Color(0xFF195221)
val OnPrimaryDarkContainerColor = Color(0xFFBDEFB9)
val SecondaryColor = Color(0xFF52634F)
val OnSecondaryColor = Color(0xFFFFFFFF)
val SecondaryContainerColor = Color(0xFFD5E8CF)
val OnSecondaryContainerColor = Color(0xFF111F0F)
val SecondaryDarkColor = Color(0xFFB7CCB1)
val OnSecondaryDarkColor = Color(0xFF243423)
val SecondaryDarkContainerColor = Color(0xFF3B4B38)
val OnSecondaryDarkContainerColor = Color(0xFFD5E8CF)
val TertiaryColor = Color(0xFF38656A)
val OnTertiaryColor = Color(0xFFFFFFFF)
val TertiaryDarkColor = Color(0xFFA1CED4)
val OnTertiaryDarkColor = Color(0xFF00363B)
val TertiaryContainerColor = Color(0xFFBCEBF0)
val TertiaryDarkContainerColor = Color(0xFF1F4D52)
val OnTertiaryContainerColor = Color(0xFF002023)
val OnTertiaryDarkContainerColor = Color(0xFFBCEBF0)
val SurfaceColor = Color(0xFFF7FBF2)
val SurfaceDarkColor = Color(0xFF111410)
val OnSurfaceColor = Color(0xFF191D18)
val OnSurfaceDarkColor = Color(0xFFE1E4DC)
val SurfaceVariantColor = Color(0xFFDEE5D9)
val SurfaceVariantDarkColor = Color(0xFFE1E4DC)
val OnSurfaceVariantColor = Color(0xFF424940)
val OnSurfaceVariantDarkColor = Color(0xFFC2C9BD)
val SurfaceDimColor = Color(0xFFDFE7D9)
val SurfaceDarkDimColor = Color(0xFF0A0E0A)
val SurfaceContainerLowestColor = Color(0xFFFFFFFF)
val SurfaceDarkContainerLowestColor = Color(0xFF0C100C)
val SurfaceContainerLowColor = Color(0xFFF5FAF0)
val SurfaceDarkContainerLowColor = Color(0xFF141914)
val SurfaceContainerColor = Color(0xFFEFF6E9)
val SurfaceDarkContainerColor = Color(0xFF191E18)
val SurfaceContainerHighColor = Color(0xFFE9F1E3)
val SurfaceDarkContainerHighColor = Color(0xFF1E231D)
val SurfaceContainerHighestColor = Color(0xFFE4EDE0)
val SurfaceDarkContainerHighestColor = Color(0xFF232822)

val OutlineColor = Color(0xFF72796F)
val OutlineDarkColor = Color(0xFF8C9388)
val OutlineVariantColor = Color(0xFFC2C9BD)
val OutlineVariantDarkColor = Color(0xFF424940)
val BackgroundColor = Color(0xFFF1F7EC)
val BackgroundDarkColor = Color(0xFF0E120E)
val ErrorColor = Color(0xFFBA1A1A)
val ErrorDarkColor = Color(0xFFFFB4AB)
val OnErrorColor = Color(0xFFFFFFFF)
val OnErrorDarkColor = Color(0xFF690005)
val ErrorContainerColor= Color(0xFFFFDAD6)
val ErrorDarkContainerColor= Color(0xFF93000A)

val OnErrorContainerColor = Color(0xFF410002)
val OnErrorDarkContainerColor = Color(0xFFFFDAD6)
