package me.ilker.balance_tracker.theme

import androidx.compose.ui.graphics.Color

val PrimaryColor = Color(0xFF326B37)
val OnPrimaryColor = Color(0xFFFFFFFF)
val PrimaryContainerColor = Color(0xFFB4F2B1)
val OnPrimaryContainerColor = Color(0xFF002105)
val PrimaryDarkColor = Color(0xFF99D597)
val OnPrimaryDarkColor = Color(0xFF00390B)
val PrimaryDarkContainerColor = Color(0xFF195221)
val OnPrimaryDarkContainerColor = Color(0xFFB4F2B1)
val SecondaryColor = Color(0xFF52634F)
val OnSecondaryColor = Color(0xFFFFFFFF)
val SecondaryContainerColor = Color(0xFFD5E8CF)
val OnSecondaryContainerColor = Color(0xFF111F0F)
val SecondaryDarkColor = Color(0xFF3B4B38)
val OnSecondaryDarkColor = Color(0xFF253423)
val SecondaryDarkContainerColor = Color(0xFF3B4B38)
val OnSecondaryDarkContainerColor = Color(0xFFD5E8CF)
val TertiaryColor = Color(0xFF38656A)
val OnTertiaryColor = Color(0xFFFFFFFF)
val TertiaryDarkColor = Color(0xFFA1CED4)
val OnTertiaryDarkColor = Color(0xFF00363B)
val TertiaryContainerColor = Color(0xFFBCEBF0)
val TertiaryDarkContainerColor = Color(0xFF1F4D52)
val OnTertiaryContainerColor = Color(0xFF002023)
val OnTertiaryDarkContainerColor = Color(0xFFBCEBF0)
val SurfaceColor = Color(0xFFF7FBF2)
val SurfaceDarkColor = Color(0xFF111410)
val OnSurfaceColor = Color(0xFF191D18)
val OnSurfaceDarkColor = Color(0xFFE1E4DC)
val SurfaceVariantColor = Color(0xFFDEE5D9)
val SurfaceVariantDarkColor = Color(0xFFE1E4DC)
val OnSurfaceVariantColor = Color(0xFF424940)
val OnSurfaceVariantDarkColor = Color(0xFFC2C9BD)

val OutlineColor = Color(0xFF72796F)
val OutlineDarkColor = Color(0xFF8C9388)
val OutlineVariantColor = Color(0xFFC2C9BD)
val OutlineVariantDarkColor = Color(0xFF424940)
val BackgroundColor = Color(0xFFC5B2B2)
val BackgroundDarkColor = Color(0xFF424141)
val ErrorColor = Color(0xFFBA1A1A)
val ErrorDarkColor = Color(0xFFFFB4AB)
val OnErrorColor = Color(0xFFFFFFFF)
val OnErrorDarkColor = Color(0xFF690005)
val ErrorContainerColor= Color(0xFFFFDAD6)
val ErrorDarkContainerColor= Color(0xFF93000A)

val OnErrorContainerColor = Color(0xFF410002)
val OnErrorDarkContainerColor = Color(0xFFFFDAD6)
